import React from 'react'
import Columns3 from './Columns3'
function Table2() {
    return (
        <div>
            <table>
                <tbody>
                <tr>
                    <Columns3/>
                </tr>
                </tbody>
            </table>
        </div>
    )
}
// Note: maintain table structure using tbody , thead, tfoot
// otherwise error
// <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> 
// to your code to match the DOM tree generated by the browser. 
export default Table2
